import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as { version: string };
const out = join(root, "src", "version.ts");

writeFileSync(
    out,
    `// Generated by scripts/generate-version.ts — do not edit\nexport const VERSION: string = ${JSON.stringify(version)};\n`,
);
